theme: minima
title: "Wanted Global test website!"
author: Wanted Global
email: ahmdnz7797@gmail.com
description: special website

# social links
twitter_username: ahmdnz7797_sy
github_username: wanted-global

show_excerpts: true
